atom_classes.py: asp/defs.lp ../common/generate_named_tuple_classes.py
	python3 ../common/generate_named_tuple_classes.py \
		--defs-path=../grid/asp/defs.lp \
		--output-path=../grid/atom_classes.py
